
sgb:
	wget https://cs.stanford.edu/pub/sgb/sgb.tar.gz	
	mkdir -p ../src
	cp sgb.tar.gz ../src/
	cd ../src && tar xf sgb.tar.gz && rm sgb.tar.gz
	
convert:
	wget https://www-cs-faculty.stanford.edu/~knuth/programs/makegraph.w
	wget https://www-cs-faculty.stanford.edu/~knuth/programs/makedigraph.w
	mkdir -p ../src
	cp makegraph.w makedigraph.w ../src/

